# Generated by Django 4.1.7 on 2023-05-27 14:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('service', models.JSONField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('place', models.CharField(choices=[('Salon', 'Salon'), ('Other', 'Other')], max_length=20)),
            ],
            options={
                'db_table': 'order_form',
            },
        ),
    ]
